module.exports.config = {
    name: "fyt",
    version: "1.0.0",
    hasPermssion: 2,
    credits: "𝐏𝐫𝐢𝐲𝐚𝐧𝐬𝐡 𝐑𝐚𝐣𝐩𝐮𝐭",
    description: "War In Chatbox",
    commandCategory: "wargroup",
    usages: "[fyt]",
    cooldowns: 7,
    dependencies: {
        "fs-extra": "",
        "axios": ""
    }
}

module.exports.run = async function({ api, args, Users, event}) {
 var mention = Object.keys(event.mentions)[0];
    
 let name =  event.mentions[mention];
    var arraytag = [];
        arraytag.push({id: mention});
    var a = function (a) { api.sendMessage(a, event.threadID); }
a("ਤੇਰੀ ਨਰੇਗਾ ਚ ਲੱਗੀ ਮਾ ਨੂੰ ਲੰਨ ਦਵਾ ਨੱਸਦਾ ਕਿੱਥੇ ਆ 😜❤️🤚❤️");
setTimeout(() => {a({body: "ਤੇਰੀ ਰਾਹ ਜਾਂਦੀ ਭੈਣ ਦੇ ਦੁੱਧੂ ਨੱਪ ਦਵਾ ਦੱਸ ਜਾਨ 😜❤️🤚" })}, 3000);
setTimeout(() => {a({body: "ਤੇਰੀ ਫੈਕਟਰੀ ਚ ਕੰਮ ਕਰਨ ਵਾਲੀ ਮਾ ਮਨਾ ਲਵਾ ਜਲਦੀ ਦੱਸ ਜਾਨ 😜❤️🤚"})}, 6000);
setTimeout(() => {a({body: "ਤੇਰੀ ਮਾ ਦੀ ਗਿੱਲੀ ਜਹੀ ਭੋਸੜੀ ਚ ਹੱਥ ਪਾ ਦਵਾ 😜❤️🤚" })}, 9000);
setTimeout(() => {a({body: "ਤੇਰੀ ਮਾ ਦੀ ਫੁੱਲਾ ਵਾਲੀ ਕੱਛੀ ਚ ਮੂਤ ਦਵਾ 😜❤️🤚" })}, 12000);
setTimeout(() => {a({body: "ਤੇਰੀ ਭੈਣ ਦੀ ਬੁੰਡ ਮਾਰੀ ਉਧਾਰੇ ਪੈਸੇ ਲੈਕੇ ਗੱਲ ਸੁਣ 😜❤️🤚" })}, 15000);
setTimeout(() => {a({body: "ਤੇਨੂੰ ਜੰਮਣ ਵਾਲੀ ਮਾ ਦੀ ਫੁੱਦੀ ਚ ਮੂਤ ਦਵਾ ਜਾਨ 😜❤️🤚" })}, 18000);
setTimeout(() => {a({body: "ਤੇਰੀ ਵੱਡੀ ਜਹੀ ਬੁੰਡ ਵਾਲੀ ਮਾ ਨਾਲ ਰੇਪ ਕਰਾ 😜❤️🤚" })}, 21000);
setTimeout(() => {a({body: "😜❤️🤚 ਕੀ ਹਾਲ ਆ ਤੇਰੀ ਗੰਦੀ ਚੁਤ ਵਾਲੀ ਮਾ ਦਾ 😾❤️" })}, 24000);
setTimeout(() => {a({body: "😜❤️🤚 ਮੈਂ ਸੁਣਿਆ ਤੇਰੀ ਮਾ ਦਿਹਾੜੀ ਚ ਬੁੰਡ ਦਿੰਦੀ ਦੋ ਵਾਰੀ ਸੱਚੀ ? 😂❤️" })}, 27000);
setTimeout(() => {a({body: "😜❤️🤚 ਤੇਰੀ ਅੱਖਾ ਤੋ ਅੰਨੀ ਮਾ ਦੀ ਟੁੱਟੀ ਜਹੀ ਐਨਕ ਚ ਲੰਨ  ਦਵਾ ਉਰੇ ਆ ☺️💖" })}, 300000);
setTimeout(() => {a({body: "😜❤️🤚 ਤੇਰੇ ਰਖੜੀ ਬੰਨਣ ਵਾਲੀ ਤੇਰੀ ਗਸਤੀ ਭੈਣ ਨੂੰ ਲੰਨ ਦਵਾ ਫੇ ☺️💖" })}, 33000);
setTimeout(() => {a({body: "" })}, 34000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂😂😂❤️❤️❤️❤️❤️" })}, 36000);
setTimeout(() => {a({body: "TTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU NNNNAASSAAAALLLL KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOOLLLLLLLLLLLAAAAAAAADDDDDD 😂😂😂😂😂❤️❤️❤️❤️😝" })}, 39000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMMMMMAAAAAA TTTTTTTTAAAAAAIIIIIILLLLLLLL LLLLLLGGGGGGGAAAAAA KKKKKKKKKAAAAAAAA LLLLAAAAND DDDDDDOIUUUUUUU 😝😝😝😂😂😂😂❤️❤️❤️❤️❤️" })}, 40000);
setTimeout(() => {a({body: "🖕🏻🖕🏻🖕🏻🖕🏻 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMAAA UUUUUUNNNNNGGGGGLLLLLIIIIIII DDDDDDOIUUUUUUU 😂😂😂😂❤️❤️❤️🖕🏻🖕🏻🖕🏻HHHHHHHHHHHHHAAAAAAAARRRRRRRRRRAAAAAAAMMMMMMMMMMM KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOLLLLLLLLAAAAAAAAADDDDDD TTTTT333333RRRRRRRR111111 BBBBB33333HHHHHHHAAAAAANNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA PPPPPPUUUUUUUSSSHHHHH KEERRROOOOUUUU 😂😂😂😂❤️❤️❤️❤️TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂😂😂❤️❤️❤️❤️❤️" })}, 43000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMMMMMAAAAAA TTTTTTTTAAAAAAIIIIIILLLLLLLL LLLLLLGGGGGGGAAAAAA KKKKKKKKKAAAAAAAA LLLLAAAAND DDDDDDOIUUUUUUU 😝😝😝😂😂😂😂❤️❤️❤️❤️❤️TTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU NNNNAASSAAAALLLL KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOOLLLLLLLLLLLAAAAAAAADDDDDD 😂😂😂😂😂❤️❤️❤️❤️😝TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂😂😂❤️❤️❤️❤️❤️HHHHHHHHHHHHHAAAAAAAARRRRRRRRRRAAAAAAAMMMMMMMMMMM KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOLLLLLLLLAAAAAAAAADDDDDD TTTTT333333RRRRRRRR111111 BBBBB33333HHHHHHHAAAAAANNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA PPPPPPUUUUUUUSSSHHHHH KEERRROOOOUUUU 😂😂😂😂❤️❤️❤️❤️🖕🏻🖕🏻🖕🏻🖕🏻 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMAAA UUUUUUNNNNNGGGGGLLLLLIIIIIII DDDDDDOIUUUUUUU 😂😂😂😂❤️❤️❤️🖕🏻🖕🏻🖕🏻" })}, 46000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 49000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 52000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 55000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 58000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 60000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 63000);
setTimeout(() => {a({body: "GGGGGGGGGGGGGGGHHHHHHAAAAAASSSSSSHHHHHHHTTTTTTTTTTIIIIIIIIIIIIIIIIIIIIIIIIIIIJ KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU 🥰🥰🥰🥰🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻☹️☹️☹️😝😝😝😝😝🤔🤔🤔🤔🤔😂😂😂😂" })} , 66000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GAAA TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KOOOOOOO LLLLAAAAND DDDDDDOIUUUUUUU GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAA 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂" })} , 69000);
setTimeout(() => {a({body: "<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GGGGGGGGGAAAAAAAA MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN CCCCCCHHHHHHOOOOOOOOODDDDDDDD:p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p" })} , 72000);
setTimeout(() => {a({body: "😆😆😆😆😆😆😆😆😆😆😆👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅👅TTTTTTEEEEEEERRRRRRRRRRRUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋U😋UU😋😋😋😋😋😋😋😋😋😋😋😋MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWKKKKKKKKKKKKKKOOOOOOOOOOOOOOOOOOOOOOOOOOOOO😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋XXXXXXXXXXXXXXXXXXXXXXXXXXXXHHHHHHHOOOOOODDDDDDDDDDDUUUUUUUUUUUUUUUUUUUUUUUUUU🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBIII*NNNNNNNNNNNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCCCCCOOOONNNNNNNNNNNNNDDDD" })} , 75000);
setTimeout(() => {a({body: "LLLLLOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣LL🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBBBBBBBBBHHHHHHHHHHHHHHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN😋N😋N😋N😋N😋N😋N😋NN😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋KKKKKKKKKIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋LLLLLLLOOOOOOOOODDDDDDDDDDDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋" })} , 78000);
setTimeout(() => {a({body: "<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GGGGGGGGGAAAAAAAA MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN CCCCCCHHHHHHOOOOOOOOODDDDDDDD:p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p" })} , 81000);
setTimeout(() => {a({body: "TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMMMMMAAAAAA TTTTTTTTAAAAAAIIIIIILLLLLLLL LLLLLLGGGGGGGAAAAAA KKKKKKKKKAAAAAAAA LLLLAAAAND DDDDDDOIUUUUUUU 😝😝😝😂😂😂😂❤️❤️❤️❤️❤️TTTTEEEXXXXXIIIII KKKKKKKKKAAAAAAAA BBBBBAAACCCCHHHAAAAA GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU NNNNAASSAAAALLLL KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOOLLLLLLLLLLLAAAAAAAADDDDDD 😂😂😂😂😂❤️❤️❤️❤️😝TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD MAROU 😂😂😂😂❤️❤️❤️❤️❤️HHHHHHHHHHHHHAAAAAAAARRRRRRRRRRAAAAAAAMMMMMMMMMMM KKKKKKKIIIIIIIIIIIIIIII OOOOOOOOOOOLLLLLLLLAAAAAAAAADDDDDD TTTTT333333RRRRRRRR111111 BBBBB33333HHHHHHHAAAAAANNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA PPPPPPUUUUUUUSSSHHHHH KEERRROOOOUUUU 😂😂😂😂❤️❤️❤️❤️🖕🏻🖕🏻🖕🏻🖕🏻 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII BBBBBBBBBBBAAAAAAHHHHHHHAAAAAAAAANNNNNNNNNNNNNNNNNNN KKKKKKKKKAAAAAAAA PPPPPPPPUUUUUUUDDDDAAAAAA MMMMMMAAA UUUUUUNNNNNGGGGGLLLLLIIIIIII DDDDDDOIUUUUUUU 😂😂😂😂❤️❤️❤️🖕🏻🖕🏻🖕🏻" })}, 84000);
setTimeout(() => {a({body: "LLLLLOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣L🤣LL🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣BBBBBBBBBBBBHHHHHHHHHHHHHHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN😋N😋N😋N😋N😋N😋N😋NN😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋KKKKKKKKKIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋LLLLLLLOOOOOOOOODDDDDDDDDDDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋" })} , 87000);
setTimeout(() => {a({body: "<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 TTTTTTTTTEEEEERRRRRRIIIIIIIIIIIII AAAAAAMMMMMMMAAAAAAAA KKKKKKKIIIIIIIIIIIIIIII LAAAALLLL GGGGGGGGGAAAAAAAANNNNNNNNDDDDD CCCCCCHHHHHHOOOOOOOOODDDDDDDD DDDDDDOIUUUUUUU GGGGGGGGGAAAAAAAA MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD GGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNDDDDDDDDDDDDDDDUUUUUUUUUUUUUU <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAAAAAAADDDDDDEEEEERRRRRRRRRRRRRR CCCCCCHHHHHHOOOOOOOOODDDDDDDD :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <3 <3 :p :p :p :p <3 <

    }
